modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Azures04/SGCraft-Reborn/issues"

[[mods]]
modId="sgcraftreborn"
version="${file.jarVersion}"
displayName="SGCraft Reborn"
displayURL="https://github.com/Azures04/SGCraft-Reborn"
logoFile= "../pack.png"
credits="Greg Ewing"
authors="Azures04, "
description='''
SG-1 Stargates and other stuff.
'''
[[dependencies.sgcraftreborn]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.sgcraftreborn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
